name: Deploy site
on:
  push:
  schedule:
    - cron: '47 4 * * 4'

jobs:
  linux1:
    name: Build site
    runs-on: ubuntu-latest
    steps:
    - name: update package database
      run: sudo apt-get update
    - name: install required packages
      run: sudo apt-get install haskell-stack php php-curl minify yui-compressor
    - name: stack update
      run: stack update
    - name: make bin directory
      run: mkdir -p /tmp/bin
    - name: install pandoc
      run: stack install pandoc --resolver lts-17.8 --local-bin-path=/tmp/bin
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: build the site
      run: make

  linux2:
    name: Look for todos
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: look for todos
      run: "! grep -i -P '<pre\\s*>|TODO|[?]{3,}' */*.md"
  
  linux3:
    name: Look for code not highlighted
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: look for todos
      run: "! grep -Pz '\n\n```\n' */*.md"

  linux4:
    name: Deploy website
    runs-on: ubuntu-latest
    needs: [linux1, linux2, linux3]
    if: github.ref == 'refs/heads/master'
    steps:
    - name: update package database
      run: sudo apt-get update
    - name: install required packages
      run: sudo apt-get install haskell-stack php php-curl minify yui-compressor
    - name: stack update
      run: stack update
    - name: make bin directory
      run: mkdir -p /tmp/bin
    - name: install pandoc
      run: stack install pandoc --resolver lts-17.8 --local-bin-path=/tmp/bin
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: build the site
      run: make
    - name: deploy site to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: out_
        single-commit: true
